### ISSUE TITLE
Breaks fonts in lot of pages

### ISSUE THREAD

**Issue by kikonen-fiksu** [rapee/jsonfinder#30] opened 2014-07-21 21:01 UTC
For example,

http://csswizardry.com/about/

With this plugin enabled, monospace font is shown, if not enabled, then correct font is shown. After some debugging I figured out that this extension is for some reason overriding font tried to be used by page.

**Comment by fibric** [comment] 2015-03-31 09:07
the problem is that jsonfinder **always** injects its style.css regardless if json data is shown or not.
fonts form style.css priorize curier new on any non mac machines.

**Comment by rapee** [comment] 2017-01-21 06:45
Fixed in 0.1.0

**Closed by rapee** 2017-01-21 06:45 UTC
